#!/usr/bin/bash

rm -rf ./generated/html

../Woboq/WoboqGen -c ../Woboq/WoboqTacent.cfg

./codebrowser_generator -a -b ./compile_commands_generated.json -o ./generated/html -p Modules:../Modules:Ver0.1
./codebrowser_indexgenerator ./generated/html
