<use f='Modules/Math/Inc/Math/tColour.h' l='802' u='w' c='_ZN9tColour4f5UnsetEv'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='803' u='r' c='_ZNK9tColour4f5IsSetEv'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='806' u='w' c='_ZN9tColour4f3SetEffff'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='807' u='w' c='_ZN9tColour4f3SetEPKf'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='808' u='w' c='_ZN9tColour4f3SetERKN5tMath8tVector3Ef'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='809' u='w' c='_ZN9tColour4f3SetERKN5tMath8tVector4E'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='817' u='w' c='_ZN9tColour4f4SetREi'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='821' u='w' c='_ZN9tColour4f6SetR16Et'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='825' u='r' c='_ZNK9tColour4f4GetREv'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='831' u='r' c='_ZNK9tColour4f3GetERN5tMath8tVector3E'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='832' u='r' c='_ZNK9tColour4f3GetERN5tMath8tVector4E'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='833' u='r' c='_ZNK9tColour4f3GetERfS0_S0_S0_'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='836' u='a' c='_ZN9tColour4f8SaturateEv'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='837' u='r' c='_ZNK9tColour4f9IntensityEv'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='839' u='w' c='_ZN9tColour4f9MakeBlackEv'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='840' u='w' c='_ZN9tColour4f9MakeWhiteEv'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='841' u='w' c='_ZN9tColour4f8MakePinkEv'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='843' u='w' c='_ZN9tColour4f7MakeRedEv'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='844' u='w' c='_ZN9tColour4f9MakeGreenEv'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='845' u='w' c='_ZN9tColour4f8MakeBlueEv'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='847' u='w' c='_ZN9tColour4f8MakeGreyEv'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='848' u='w' c='_ZN9tColour4f13MakeLightGreyEv'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='849' u='w' c='_ZN9tColour4f12MakeDarkGreyEv'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='851' u='w' c='_ZN9tColour4f8MakeCyanEv'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='852' u='w' c='_ZN9tColour4f11MakeMagentaEv'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='853' u='w' c='_ZN9tColour4f10MakeYellowEv'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='856' u='r' c='_ZNK9tColour4f7IsBlackEv'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='857' u='r' c='_ZNK9tColour4f7IsWhiteEv'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='858' u='r' c='_ZNK9tColour4f5IsRedEv'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='859' u='r' c='_ZNK9tColour4f7IsGreenEv'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='860' u='r' c='_ZNK9tColour4f6IsBlueEv'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='863' u='r' c='_ZNK9tColour4f5IsHDREv'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='909' u='w' c='_ZN9tColour4fmLEf'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='911' u='w' c='_ZN9tColour4fpLERKS_'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='911' u='r' c='_ZN9tColour4fpLERKS_'/>
<dec f='Modules/Math/Inc/Math/tColour.h' l='936' type='float'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='1092' u='r' c='_ZN9tColour4b3SetERK9tColour4f'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='1184' u='r' c='_ZN9tColour4s3SetERK9tColour4f'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='1232' u='r' c='_ZNK9tColour3feqERK9tColour4f'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='1238' u='r' c='_ZNK9tColour3fneERK9tColour4f'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='1250' u='w' c='_ZN9tColour4f14SquareToLinearEj'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='1250' u='r' c='_ZN9tColour4f14SquareToLinearEj'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='1259' u='w' c='_ZN9tColour4f14LinearToSquareEj'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='1259' u='r' c='_ZN9tColour4f14LinearToSquareEj'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='1268' u='w' c='_ZN9tColour4f13GammaToLinearEfj'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='1268' u='r' c='_ZN9tColour4f13GammaToLinearEfj'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='1277' u='w' c='_ZN9tColour4f13LinearToGammaEfj'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='1277' u='r' c='_ZN9tColour4f13LinearToGammaEfj'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='1286' u='w' c='_ZN9tColour4f12SRGBToLinearEj'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='1286' u='r' c='_ZN9tColour4f12SRGBToLinearEj'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='1295' u='w' c='_ZN9tColour4f12LinearToSRGBEj'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='1295' u='r' c='_ZN9tColour4f12LinearToSRGBEj'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='1304' u='w' c='_ZN9tColour4f15TonemapExposureEfj'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='1304' u='r' c='_ZN9tColour4f15TonemapExposureEfj'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='1313' u='w' c='_ZN9tColour4f15TonemapReinhardEj'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='1313' u='r' c='_ZN9tColour4f15TonemapReinhardEj'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='1322' u='r' c='_ZN9tColour4f8RGBToHSVEv'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='1334' u='a' c='_ZN9tColour4f8HSVToRGBEv'/>
<offset>0</offset>
<use f='Modules/Image/Inc/Image/tPicture.h' l='634' u='w' c='_ZN6tImage8tPicture16AlphaBlendColourERK9tColour4bji'/>
<use f='Modules/Image/Inc/Image/tPicture.h' l='634' u='r' c='_ZN6tImage8tPicture16AlphaBlendColourERK9tColour4bji'/>
<use f='Modules/Image/Inc/Image/tPicture.h' l='634' u='r' c='_ZN6tImage8tPicture16AlphaBlendColourERK9tColour4bji'/>
<use f='Modules/Image/Src/tImageDDS.cpp' l='1485' u='r' c='_ZN6tImage9tImageDDS4LoadEPKhiRKNS0_10LoadParamsE'/>
<use f='Modules/Image/Src/tImageKTX.cpp' l='1067' u='r' c='_ZN6tImage9tImageKTX15LoadFromTextureEP10ktxTextureRKNS0_10LoadParamsE'/>
<use f='Modules/Image/Src/tImagePKM.cpp' l='247' u='r' c='_ZN6tImage9tImagePKM4LoadEPKhiRKNS0_10LoadParamsE'/>
<use f='Modules/Image/Src/tImagePNG.cpp' l='393' u='r' c='_ZN6tImage9tImagePNG4LoadEPKhiRKNS0_10LoadParamsE'/>
<use f='Modules/Image/Src/tImagePNG.cpp' l='407' u='r' c='_ZN6tImage9tImagePNG4LoadEPKhiRKNS0_10LoadParamsE'/>
<use f='Modules/Image/Src/tImagePVR.cpp' l='1177' u='r' c='_ZN6tImage9tImagePVR14CreateNewLayerERKNS0_10LoadParamsEPKhiii'/>
<use f='Modules/Image/Src/tImageWEBP.cpp' l='201' u='w' c='_ZN6tImage10tImageWEBP10CopyRegionEP9tColour4biiS2_iiiib'/>
<use f='Modules/Image/Src/tImageWEBP.cpp' l='201' u='r' c='_ZN6tImage10tImageWEBP10CopyRegionEP9tColour4biiS2_iiiib'/>
<use f='Modules/Image/Src/tImageWEBP.cpp' l='201' u='r' c='_ZN6tImage10tImageWEBP10CopyRegionEP9tColour4biiS2_iiiib'/>
