<dec f='Modules/Math/Inc/Math/tColour.h' l='480' type='uint8[4]'/>
<offset>0</offset>
<doc f='Modules/Math/Inc/Math/tColour.h' l='479'>// Individual elements. Makes it easy to submit colours to OpenGL using glColor3ubv.</doc>
<use f='Modules/Image/Src/tImageHDR.cpp' l='181' u='w' c='_ZN6tImage9tImageHDR19ReadRadianceColoursEP9tColour4bi'/>
<use f='Modules/Image/Src/tImageHDR.cpp' l='193' u='w' c='_ZN6tImage9tImageHDR19ReadRadianceColoursEP9tColour4bi'/>
<use f='Modules/Image/Src/tPicture.cpp' l='805' u='r' c='_ZN6tImage8tPicture12AdjustLevelsEfffffbj'/>
<use f='Modules/Image/Src/tPicture.cpp' l='815' u='w' c='_ZN6tImage8tPicture12AdjustLevelsEfffffbj'/>
<use f='Modules/System/Src/tScript.cpp' l='942' u='r' c='_ZN11tExprWriter9WriteAtomERK9tColour4b'/>
