<use f='Modules/Math/Inc/Math/tColour.h' l='355' u='w' c='_ZN9tColour4b3SetEiiii'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='356' u='w' c='_ZN9tColour4b3SetEhhhh'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='366' u='w' c='_ZN9tColour4b6SetRGBEiii'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='367' u='w' c='_ZN9tColour4b6SetRGBEhhh'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='371' u='w' c='_ZN9tColour4b4SetREf'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='377' u='r' c='_ZNK9tColour4b4GetREv'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='387' u='r' c='_ZNK9tColour4b10GetDenormREv'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='401' u='w' c='_ZN9tColour4b8MakeZeroEv'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='402' u='w' c='_ZN9tColour4b9MakeBlackEv'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='403' u='w' c='_ZN9tColour4b9MakeWhiteEv'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='404' u='w' c='_ZN9tColour4b8MakePinkEv'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='406' u='w' c='_ZN9tColour4b7MakeRedEv'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='407' u='w' c='_ZN9tColour4b9MakeGreenEv'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='408' u='w' c='_ZN9tColour4b8MakeBlueEv'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='410' u='w' c='_ZN9tColour4b8MakeGreyEv'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='411' u='w' c='_ZN9tColour4b13MakeLightGreyEv'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='412' u='w' c='_ZN9tColour4b12MakeDarkGreyEv'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='414' u='w' c='_ZN9tColour4b8MakeCyanEv'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='415' u='w' c='_ZN9tColour4b11MakeMagentaEv'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='416' u='w' c='_ZN9tColour4b10MakeYellowEv'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='419' u='r' c='_ZNK9tColour4b7IsBlackEv'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='420' u='r' c='_ZNK9tColour4b7IsWhiteEv'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='421' u='r' c='_ZNK9tColour4b5IsRedEv'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='422' u='r' c='_ZNK9tColour4b7IsGreenEv'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='423' u='r' c='_ZNK9tColour4b6IsBlueEv'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='438' u='w' c='_ZN9tColour4bmLEf'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='438' u='r' c='_ZN9tColour4bmLEf'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='440' u='w' c='_ZN9tColour4bpLERKS_'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='440' u='r' c='_ZN9tColour4bpLERKS_'/>
<dec f='Modules/Math/Inc/Math/tColour.h' l='469' type='uint8'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='695' u='r' c='_ZN9tColour3f3SetERK9tColour4b'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='810' u='r' c='_ZN9tColour4f3SetERK9tColour4b'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='1068' u='w' c='_ZN9tColour4b3SetERK9tColour3bi'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='1074' u='w' c='_ZN9tColour4b3SetERK9tColour4s'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='1083' u='w' c='_ZN9tColour4b3SetERK9tColour3st'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='1111' u='r' c='_ZNK9tColour4b9IntensityEj'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='1122' u='r' c='_ZN9tColour4b8RGBToHSVEv'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='1140' u='w' c='_ZN9tColour4b8HSVToRGBEv'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='1148' u='r' c='_ZNK9tColour4b5EqualERKS_j'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='1148' u='r' c='_ZNK9tColour4b5EqualERKS_j'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='1166' u='r' c='_ZN9tColour4s3SetERK9tColour4b'/>
<offset>0</offset>
<use f='Modules/Image/Inc/Image/tPicture.h' l='496' u='w' c='_ZN6tImage8tPicture8SetPixelEiiRK9tColour4bj'/>
<use f='Modules/Image/Inc/Image/tPicture.h' l='496' u='r' c='_ZN6tImage8tPicture8SetPixelEiiRK9tColour4bj'/>
<use f='Modules/Image/Inc/Image/tPicture.h' l='518' u='w' c='_ZN6tImage8tPicture6SetAllERK9tColour4bj'/>
<use f='Modules/Image/Inc/Image/tPicture.h' l='518' u='r' c='_ZN6tImage8tPicture6SetAllERK9tColour4bj'/>
<use f='Modules/Image/Inc/Image/tPicture.h' l='535' u='r' c='_ZN6tImage8tPicture6SpreadE5tComp'/>
<use f='Modules/Image/Inc/Image/tPicture.h' l='536' u='w' c='_ZN6tImage8tPicture6SpreadE5tComp'/>
<use f='Modules/Image/Inc/Image/tPicture.h' l='537' u='w' c='_ZN6tImage8tPicture6SpreadE5tComp'/>
<use f='Modules/Image/Inc/Image/tPicture.h' l='538' u='w' c='_ZN6tImage8tPicture6SpreadE5tComp'/>
<use f='Modules/Image/Inc/Image/tPicture.h' l='565' u='r' c='_ZN6tImage8tPicture7SwizzleE5tCompS1_S1_S1_'/>
<use f='Modules/Image/Inc/Image/tPicture.h' l='573' u='r' c='_ZN6tImage8tPicture7SwizzleE5tCompS1_S1_S1_'/>
<use f='Modules/Image/Inc/Image/tPicture.h' l='581' u='r' c='_ZN6tImage8tPicture7SwizzleE5tCompS1_S1_S1_'/>
<use f='Modules/Image/Inc/Image/tPicture.h' l='589' u='r' c='_ZN6tImage8tPicture7SwizzleE5tCompS1_S1_S1_'/>
<use f='Modules/Image/Inc/Image/tPicture.h' l='611' u='w' c='_ZN6tImage8tPicture9IntensityEj'/>
<use f='Modules/Image/Src/tImageAPNG.cpp' l='288' u='r' c='_ZNK6tImage10tImageAPNG4SaveERK7tStringRKNS0_10SaveParamsE'/>
<use f='Modules/Image/Src/tImageDDS.cpp' l='1508' u='r' c='_ZN6tImage9tImageDDS4LoadEPKhiRKNS0_10LoadParamsE'/>
<use f='Modules/Image/Src/tImageDDS.cpp' l='1509' u='r' c='_ZN6tImage9tImageDDS4LoadEPKhiRKNS0_10LoadParamsE'/>
<use f='Modules/Image/Src/tImageDDS.cpp' l='1532' u='a' c='_ZN6tImage9tImageDDS4LoadEPKhiRKNS0_10LoadParamsE'/>
<use f='Modules/Image/Src/tImageHDR.cpp' l='103' u='w' c='_ZN6tImage9tImageHDR25LegacyReadRadianceColoursEP9tColour4bi'/>
<use f='Modules/Image/Src/tImageHDR.cpp' l='109' u='r' c='_ZN6tImage9tImageHDR25LegacyReadRadianceColoursEP9tColour4bi'/>
<use f='Modules/Image/Src/tImageHDR.cpp' l='155' u='w' c='_ZN6tImage9tImageHDR19ReadRadianceColoursEP9tColour4bi'/>
<use f='Modules/Image/Src/tImageHDR.cpp' l='219' u='w' c='_ZN6tImage9tImageHDR31ConvertRadianceToGammaCorrectedEP9tColour4bi'/>
<use f='Modules/Image/Src/tImageHDR.cpp' l='219' u='r' c='_ZN6tImage9tImageHDR31ConvertRadianceToGammaCorrectedEP9tColour4bi'/>
<use f='Modules/Image/Src/tImageHDR.cpp' l='233' u='r' c='_ZN6tImage9tImageHDR31ConvertRadianceToGammaCorrectedEP9tColour4bi'/>
<use f='Modules/Image/Src/tImageHDR.cpp' l='233' u='w' c='_ZN6tImage9tImageHDR31ConvertRadianceToGammaCorrectedEP9tColour4bi'/>
<use f='Modules/Image/Src/tImageHDR.cpp' l='240' u='w' c='_ZN6tImage9tImageHDR31ConvertRadianceToGammaCorrectedEP9tColour4bi'/>
<use f='Modules/Image/Src/tImageHDR.cpp' l='240' u='r' c='_ZN6tImage9tImageHDR31ConvertRadianceToGammaCorrectedEP9tColour4bi'/>
<use f='Modules/Image/Src/tImageHDR.cpp' l='368' u='r' c='_ZN6tImage9tImageHDR4LoadEPhiRKNS0_10LoadParamsE'/>
<use f='Modules/Image/Src/tImageKTX.cpp' l='1090' u='r' c='_ZN6tImage9tImageKTX15LoadFromTextureEP10ktxTextureRKNS0_10LoadParamsE'/>
<use f='Modules/Image/Src/tImageKTX.cpp' l='1091' u='r' c='_ZN6tImage9tImageKTX15LoadFromTextureEP10ktxTextureRKNS0_10LoadParamsE'/>
<use f='Modules/Image/Src/tImageKTX.cpp' l='1114' u='a' c='_ZN6tImage9tImageKTX15LoadFromTextureEP10ktxTextureRKNS0_10LoadParamsE'/>
<use f='Modules/Image/Src/tImagePKM.cpp' l='268' u='r' c='_ZN6tImage9tImagePKM4LoadEPKhiRKNS0_10LoadParamsE'/>
<use f='Modules/Image/Src/tImagePKM.cpp' l='269' u='r' c='_ZN6tImage9tImagePKM4LoadEPKhiRKNS0_10LoadParamsE'/>
<use f='Modules/Image/Src/tImagePNG.cpp' l='788' u='r' c='_ZNK6tImage9tImagePNG4SaveERK7tStringRKNS0_10SaveParamsE'/>
<use f='Modules/Image/Src/tImagePNG.cpp' l='803' u='r' c='_ZNK6tImage9tImagePNG4SaveERK7tStringRKNS0_10SaveParamsE'/>
<use f='Modules/Image/Src/tImagePVR.cpp' l='1200' u='r' c='_ZN6tImage9tImagePVR14CreateNewLayerERKNS0_10LoadParamsEPKhiii'/>
<use f='Modules/Image/Src/tImagePVR.cpp' l='1201' u='r' c='_ZN6tImage9tImagePVR14CreateNewLayerERKNS0_10LoadParamsEPKhiii'/>
<use f='Modules/Image/Src/tImageQOI.cpp' l='226' u='r' c='_ZNK6tImage9tImageQOI4SaveERK7tStringRKNS0_10SaveParamsE'/>
<use f='Modules/Image/Src/tImageTGA.cpp' l='243' u='w' c='_ZN6tImage9tImageTGA15ReadColourBytesER9tColour4bPKhib'/>
<use f='Modules/Image/Src/tImageTGA.cpp' l='250' u='w' c='_ZN6tImage9tImageTGA15ReadColourBytesER9tColour4bPKhib'/>
<use f='Modules/Image/Src/tImageTGA.cpp' l='257' u='w' c='_ZN6tImage9tImageTGA15ReadColourBytesER9tColour4bPKhib'/>
<use f='Modules/Image/Src/tImageTGA.cpp' l='453' u='r' c='_ZNK6tImage9tImageTGA16SaveUncompressedERK7tStringNS0_7tFormatE'/>
<use f='Modules/Image/Src/tImageTGA.cpp' l='518' u='r' c='_ZNK6tImage9tImageTGA14SaveCompressedERK7tStringNS0_7tFormatE'/>
<use f='Modules/Image/Src/tImageTGA.cpp' l='529' u='r' c='_ZNK6tImage9tImageTGA14SaveCompressedERK7tStringNS0_7tFormatE'/>
<use f='Modules/Image/Src/tImageTGA.cpp' l='551' u='r' c='_ZNK6tImage9tImageTGA14SaveCompressedERK7tStringNS0_7tFormatE'/>
<use f='Modules/Image/Src/tImageTIFF.cpp' l='321' u='r' c='_ZNK6tImage10tImageTIFF4SaveERK7tStringRKNS0_10SaveParamsE'/>
<use f='Modules/Image/Src/tImageWEBP.cpp' l='76' u='w' c='_ZN6tImage10tImageWEBP4LoadEPKhi'/>
<use f='Modules/Image/Src/tPaletteImage.cpp' l='109' u='r' c='_ZN6tImage13tPaletteImage3SetENS_12tPixelFormatEiiPK9tColour4bNS_9tQuantize6MethodE'/>
<use f='Modules/Image/Src/tPicture.cpp' l='646' u='r' c='_ZN6tImage8tPicture15AdjustmentBeginEv'/>
<use f='Modules/Image/Src/tPicture.cpp' l='647' u='r' c='_ZN6tImage8tPicture15AdjustmentBeginEv'/>
<use f='Modules/Image/Src/tPicture.cpp' l='655' u='r' c='_ZN6tImage8tPicture15AdjustmentBeginEv'/>
<use f='Modules/Image/Src/tPicture.cpp' l='697' u='w' c='_ZN6tImage8tPicture16AdjustBrightnessEfj'/>
<use f='Modules/Image/Src/tPicture.cpp' l='697' u='r' c='_ZN6tImage8tPicture16AdjustBrightnessEfj'/>
<use f='Modules/Image/Src/tPicture.cpp' l='732' u='w' c='_ZN6tImage8tPicture14AdjustContrastEfj'/>
<use f='Modules/Image/Src/tPicture.cpp' l='732' u='r' c='_ZN6tImage8tPicture14AdjustContrastEfj'/>
<use f='Modules/Image/Src/tPicture.cpp' l='889' u='r' c='_ZN6tImage8tPicture9ScaleHalfEv'/>
<use f='Modules/Image/Src/tPicture.cpp' l='890' u='r' c='_ZN6tImage8tPicture9ScaleHalfEv'/>
<use f='Modules/Image/Src/tPicture.cpp' l='891' u='w' c='_ZN6tImage8tPicture9ScaleHalfEv'/>
<use f='Modules/Image/Src/tPicture.cpp' l='918' u='r' c='_ZN6tImage8tPicture9ScaleHalfEv'/>
<use f='Modules/Image/Src/tPicture.cpp' l='919' u='r' c='_ZN6tImage8tPicture9ScaleHalfEv'/>
<use f='Modules/Image/Src/tPicture.cpp' l='920' u='r' c='_ZN6tImage8tPicture9ScaleHalfEv'/>
<use f='Modules/Image/Src/tPicture.cpp' l='921' u='r' c='_ZN6tImage8tPicture9ScaleHalfEv'/>
<use f='Modules/Image/Src/tPicture.cpp' l='922' u='w' c='_ZN6tImage8tPicture9ScaleHalfEv'/>
<use f='Modules/Image/Src/tQuantizeFixed.cpp' l='343' u='r' c='_ZN6tImage14tQuantizeFixed13QuantizeImageEiiiPK9tColour4bP9tColour3bPhb'/>
<use f='Modules/Image/Src/tQuantizeNeu.cpp' l='593' u='r' c='_ZN6tImage12tQuantizeNeu13QuantizeImageEiiiPK9tColour4bP9tColour3bPhbi'/>
<use f='Modules/Image/Src/tQuantizeSpatial.cpp' l='951' u='r' c='_ZN6tImage16tQuantizeSpatial13QuantizeImageEiiiPK9tColour4bP9tColour3bPhbdi'/>
<use f='Modules/Image/Src/tQuantizeWu.cpp' l='564' u='r' c='_ZN6tImage11tQuantizeWu13QuantizeImageEiiiPK9tColour4bP9tColour3bPhb'/>
<use f='Modules/Image/Src/tResample.cpp' l='285' u='r' c='_ZN6tImage15KernelFilterBoxEPK9tColour4biiffNS_15FilterDirectionENS_17tResampleEdgeModeERKNS_12FilterParamsE'/>
<use f='Modules/Image/Src/tResample.cpp' l='399' u='r' c='_ZN6tImage19KernelFilterBicubicEPK9tColour4biiffNS_15FilterDirectionENS_17tResampleEdgeModeERKNS_12FilterParamsE'/>
<use f='Modules/Image/Src/tResample.cpp' l='447' u='r' c='_ZN6tImage19KernelFilterLanczosEPK9tColour4biiffNS_15FilterDirectionENS_17tResampleEdgeModeERKNS_12FilterParamsE'/>
<use f='Modules/Image/Src/tTexture.cpp' l='258' u='r' c='_ZN6tImage8tTexture23ProcessImageTo_G3B5R5G3ERNS_8tPictureEbNS0_8tQualityE'/>
<use f='Modules/Scene/Inc/Scene/tMaterial.h' l='38' u='r' c='_ZNK6tScene9tMaterial10GetOpacityEv'/>
<use f='Modules/System/Src/tScript.cpp' l='408' u='w' c='_ZNK11tExpression13GetAtomColourEv'/>
