<dec f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='27' type='1'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='28'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='64' u='r'/>
<use f='Modules/Image/Inc/Image/tPicture.h' l='166' c='_ZN6tImage8tPicture7SwizzleE5tCompS1_S1_S1_'/>
<use f='Modules/Image/Inc/Image/tPicture.h' l='536' c='_ZN6tImage8tPicture6SpreadE5tComp'/>
<use f='Modules/Image/Inc/Image/tPicture.h' l='166' c='_ZN6tImage8tPicture7SwizzleE5tCompS1_S1_S1_'/>
<use f='Modules/Image/Inc/Image/tPicture.h' l='550' u='r' c='_ZN6tImage8tPicture7SwizzleE5tCompS1_S1_S1_'/>
<use f='Modules/Image/Inc/Image/tPicture.h' l='554' u='r' c='_ZN6tImage8tPicture7SwizzleE5tCompS1_S1_S1_'/>
<use f='Modules/Image/Inc/Image/tPicture.h' l='566' u='r' c='_ZN6tImage8tPicture7SwizzleE5tCompS1_S1_S1_'/>
<use f='Modules/Image/Inc/Image/tPicture.h' l='574' u='r' c='_ZN6tImage8tPicture7SwizzleE5tCompS1_S1_S1_'/>
<use f='Modules/Image/Inc/Image/tPicture.h' l='582' u='r' c='_ZN6tImage8tPicture7SwizzleE5tCompS1_S1_S1_'/>
<use f='Modules/Image/Inc/Image/tPicture.h' l='590' u='r' c='_ZN6tImage8tPicture7SwizzleE5tCompS1_S1_S1_'/>
