<dec f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='27' type='2'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='28'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='65' u='r'/>
<use f='Modules/Image/Inc/Image/tPicture.h' l='166' c='_ZN6tImage8tPicture7SwizzleE5tCompS1_S1_S1_'/>
<use f='Modules/Image/Inc/Image/tPicture.h' l='537' c='_ZN6tImage8tPicture6SpreadE5tComp'/>
<use f='Modules/Image/Inc/Image/tPicture.h' l='166' c='_ZN6tImage8tPicture7SwizzleE5tCompS1_S1_S1_'/>
<use f='Modules/Image/Inc/Image/tPicture.h' l='551' u='r' c='_ZN6tImage8tPicture7SwizzleE5tCompS1_S1_S1_'/>
<use f='Modules/Image/Inc/Image/tPicture.h' l='554' u='r' c='_ZN6tImage8tPicture7SwizzleE5tCompS1_S1_S1_'/>
<use f='Modules/Image/Inc/Image/tPicture.h' l='567' u='r' c='_ZN6tImage8tPicture7SwizzleE5tCompS1_S1_S1_'/>
<use f='Modules/Image/Inc/Image/tPicture.h' l='575' u='r' c='_ZN6tImage8tPicture7SwizzleE5tCompS1_S1_S1_'/>
<use f='Modules/Image/Inc/Image/tPicture.h' l='583' u='r' c='_ZN6tImage8tPicture7SwizzleE5tCompS1_S1_S1_'/>
<use f='Modules/Image/Inc/Image/tPicture.h' l='591' u='r' c='_ZN6tImage8tPicture7SwizzleE5tCompS1_S1_S1_'/>
