<dec f='Modules/Image/Inc/Image/tMetaData.h' l='34' type='0'/>
<doc f='Modules/Image/Inc/Image/tMetaData.h' l='33'>// Camera Hardware Tags</doc>
<doc f='Modules/Image/Inc/Image/tMetaData.h' l='34'>//	string	Camera make. eg. &quot;Canon&quot;.</doc>
<use f='Modules/Image/Src/tMetaData.cpp' l='230' u='m' c='_ZN6tImage9tMetaData19SetTags_CamHardwareERKN8TinyEXIF8EXIFInfoE'/>
<use f='Modules/Image/Src/tMetaData.cpp' l='656' c='_ZNK6tImage9tMetaData14GetPrettyValueENS_8tMetaTagE'/>
