<dec f='Modules/Math/Inc/Math/tVector3.h' l='105' type='const tMath::tVector3'/>
<doc f='Modules/Math/Inc/Math/tVector3.h' l='105'>// Basis vector (0, 0, 1).</doc>
<def f='Modules/Math/Src/tLinearAlgebra.cpp' l='47' type='const tMath::tVector3'/>
<use f='Modules/Math/Src/tRandom.cpp' l='191' u='r' c='_ZN5tMath7tRandom14tGetPointOnBoxERKNS_5tABoxERKNS0_10tGeneratorE'/>
<use f='Modules/Math/Src/tRandom.cpp' l='199' u='r' c='_ZN5tMath7tRandom14tGetPointOnBoxERKNS_5tABoxERKNS0_10tGeneratorE'/>
<use f='Modules/Math/Src/tRandom.cpp' l='205' u='r' c='_ZN5tMath7tRandom14tGetPointOnBoxERKNS_5tABoxERKNS0_10tGeneratorE'/>
