<dec f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='136' type='float'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='218' u='w' c='_ZN5tMath4tSetERNS_5tVec4ERKNS_5tVec2Eff'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='219' u='w' c='_ZN5tMath4tSetERNS_5tVec4ERKNS_5tVec3Ef'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='220' u='w' c='_ZN5tMath4tSetERNS_5tVec4ERKS0_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='220' u='r' c='_ZN5tMath4tSetERNS_5tVec4ERKS0_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='221' u='w' c='_ZN5tMath4tSetERNS_5tVec4Ef'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='222' u='w' c='_ZN5tMath4tSetERNS_5tVec4Effff'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='223' u='w' c='_ZN5tMath4tSetERNS_5tVec4EPKf'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='254' u='r' c='_ZN5tMath4tGetERfS0_S0_S0_RKNS_5tVec4E'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='255' u='r' c='_ZN5tMath4tGetEPfRKNS_5tVec4E'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='275' u='w' c='_ZN5tMath5tZeroERNS_5tVec4E'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='276' u='w' c='_ZN5tMath5tZeroERNS_5tVec4Ej'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='288' u='r' c='_ZN5tMath7tIsZeroERKNS_5tVec4E'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='289' u='r' c='_ZN5tMath7tIsZeroERKNS_5tVec4Ej'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='303' u='r' c='_ZN5tMath12tApproxEqualERKNS_5tVec4ES2_f'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='303' u='r' c='_ZN5tMath12tApproxEqualERKNS_5tVec4ES2_f'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='304' u='r' c='_ZN5tMath12tApproxEqualERKNS_5tVec4ES2_jf'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='304' u='r' c='_ZN5tMath12tApproxEqualERKNS_5tVec4ES2_jf'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='316' u='r' c='_ZN5tMath6tEqualERKNS_5tVec4ES2_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='316' u='r' c='_ZN5tMath6tEqualERKNS_5tVec4ES2_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='317' u='r' c='_ZN5tMath6tEqualERKNS_5tVec4ES2_j'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='317' u='r' c='_ZN5tMath6tEqualERKNS_5tVec4ES2_j'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='329' u='r' c='_ZN5tMath9tNotEqualERKNS_5tVec4ES2_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='329' u='r' c='_ZN5tMath9tNotEqualERKNS_5tVec4ES2_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='330' u='r' c='_ZN5tMath9tNotEqualERKNS_5tVec4ES2_j'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='330' u='r' c='_ZN5tMath9tNotEqualERKNS_5tVec4ES2_j'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='340' u='r' c='_ZN5tMath9tLengthSqERKNS_5tVec4E'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='340' u='r' c='_ZN5tMath9tLengthSqERKNS_5tVec4E'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='355' u='w' c='_ZN5tMath10tNormalizeERNS_5tVec4E'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='360' u='w' c='_ZN5tMath19tNormalizeGetLengthERNS_5tVec4E'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='365' u='w' c='_ZN5tMath14tNormalizeSafeERNS_5tVec4E'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='370' u='w' c='_ZN5tMath23tNormalizeSafeGetLengthERNS_5tVec4E'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='375' u='w' c='_ZN5tMath15tNormalizeScaleERNS_5tVec4Ef'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='379' u='w' c='_ZN5tMath19tNormalizeScaleSafeERNS_5tVec4Ef'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='383' u='w' c='_ZN5tMath14tNormalizeFastERNS_5tVec4E'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='388' u='w' c='_ZN5tMath18tNormalizeSafeFastERNS_5tVec4E'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='396' u='w' c='_ZN5tMath4tAddERNS_5tVec4ERKS0_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='396' u='r' c='_ZN5tMath4tAddERNS_5tVec4ERKS0_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='397' u='w' c='_ZN5tMath4tAddERNS_5tVec4ERKS0_S3_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='397' u='r' c='_ZN5tMath4tAddERNS_5tVec4ERKS0_S3_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='397' u='r' c='_ZN5tMath4tAddERNS_5tVec4ERKS0_S3_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='410' u='w' c='_ZN5tMath4tSubERNS_5tVec4ERKS0_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='410' u='r' c='_ZN5tMath4tSubERNS_5tVec4ERKS0_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='411' u='w' c='_ZN5tMath4tSubERNS_5tVec4ERKS0_S3_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='411' u='r' c='_ZN5tMath4tSubERNS_5tVec4ERKS0_S3_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='411' u='r' c='_ZN5tMath4tSubERNS_5tVec4ERKS0_S3_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='424' u='w' c='_ZN5tMath4tNegERNS_5tVec4E'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='424' u='r' c='_ZN5tMath4tNegERNS_5tVec4E'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='425' u='w' c='_ZN5tMath4tNegERNS_5tVec4ERKS0_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='425' u='r' c='_ZN5tMath4tNegERNS_5tVec4ERKS0_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='450' u='w' c='_ZN5tMath4tMulERNS_5tVec4Ef'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='451' u='w' c='_ZN5tMath4tMulERNS_5tVec4ERKS0_f'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='451' u='r' c='_ZN5tMath4tMulERNS_5tVec4ERKS0_f'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='452' u='w' c='_ZN5tMath4tMulERNS_5tVec4EfRKS0_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='452' u='r' c='_ZN5tMath4tMulERNS_5tVec4EfRKS0_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='483' u='w' c='_ZN5tMath5tMulEERNS_5tVec4ERKS0_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='483' u='r' c='_ZN5tMath5tMulEERNS_5tVec4ERKS0_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='484' u='w' c='_ZN5tMath5tMulEERNS_5tVec4ERKS0_S3_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='484' u='r' c='_ZN5tMath5tMulEERNS_5tVec4ERKS0_S3_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='484' u='r' c='_ZN5tMath5tMulEERNS_5tVec4ERKS0_S3_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='495' u='w' c='_ZN5tMath4tDivERNS_5tVec4Ef'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='496' u='w' c='_ZN5tMath4tDivERNS_5tVec4ERKS0_f'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='496' u='r' c='_ZN5tMath4tDivERNS_5tVec4ERKS0_f'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='509' u='w' c='_ZN5tMath5tDivEERNS_5tVec4ERKS0_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='509' u='r' c='_ZN5tMath5tDivEERNS_5tVec4ERKS0_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='510' u='w' c='_ZN5tMath5tDivEERNS_5tVec4ERKS0_S3_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='510' u='r' c='_ZN5tMath5tDivEERNS_5tVec4ERKS0_S3_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='510' u='r' c='_ZN5tMath5tDivEERNS_5tVec4ERKS0_S3_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='518' u='r' c='_ZN5tMath4tDotERKNS_5tVec4ES2_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='518' u='r' c='_ZN5tMath4tDotERKNS_5tVec4ES2_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='526' u='w' c='_ZN5tMath5tLerpERNS_5tVec4ERKS0_S3_f'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='526' u='r' c='_ZN5tMath5tLerpERNS_5tVec4ERKS0_S3_f'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='526' u='r' c='_ZN5tMath5tLerpERNS_5tVec4ERKS0_S3_f'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='1086' u='r' c='_ZN5tMath15tMulByTransposeERNS_5tMat4ERKNS_5tVec4ES4_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='1087' u='r' c='_ZN5tMath15tMulByTransposeERNS_5tMat4ERKNS_5tVec4ES4_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='1088' u='r' c='_ZN5tMath15tMulByTransposeERNS_5tMat4ERKNS_5tVec4ES4_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='1089' u='r' c='_ZN5tMath15tMulByTransposeERNS_5tMat4ERKNS_5tVec4ES4_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='1089' u='r' c='_ZN5tMath15tMulByTransposeERNS_5tMat4ERKNS_5tVec4ES4_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='1089' u='r' c='_ZN5tMath15tMulByTransposeERNS_5tMat4ERKNS_5tVec4ES4_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='1089' u='r' c='_ZN5tMath15tMulByTransposeERNS_5tMat4ERKNS_5tVec4ES4_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='1089' u='r' c='_ZN5tMath15tMulByTransposeERNS_5tMat4ERKNS_5tVec4ES4_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='1178' u='w' c='_ZN5tMath6tCrossERNS_5tVec4ERKS0_S3_'/>
<use f='Modules/Math/Inc/Math/tVector4.h' l='66' u='r' c='_ZNK5tMath8tVector412GetCartesianEv'/>
<use f='Modules/Math/Inc/Math/tVector4.h' l='66' u='r' c='_ZNK5tMath8tVector412GetCartesianEv'/>
<use f='Modules/Math/Inc/Math/tVector4.h' l='66' u='r' c='_ZNK5tMath8tVector412GetCartesianEv'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='383' u='w' c='_ZNK9tColour4b3GetERN5tMath8tVector4E'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='393' u='w' c='_ZNK9tColour4b9GetDenormERN5tMath8tVector4E'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='576' u='w' c='_ZNK9tColour4s3GetERN5tMath8tVector4E'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='586' u='w' c='_ZNK9tColour4s9GetDenormERN5tMath8tVector4E'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='708' u='w' c='_ZNK9tColour3f3GetERN5tMath8tVector4E'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='809' u='r' c='_ZN9tColour4f3SetERKN5tMath8tVector4E'/>
<use f='Modules/Math/Inc/Math/tColour.h' l='832' u='w' c='_ZNK9tColour4f3GetERN5tMath8tVector4E'/>
<offset>96</offset>
<use f='Modules/Math/Inc/Math/tGeometry.h' l='375' u='r' c='_ZN5tMath6tPlane3SetERKNS_8tVector4E'/>
<use f='Modules/Image/Src/tResample.cpp' l='288' u='w' c='_ZN6tImage15KernelFilterBoxEPK9tColour4biiffNS_15FilterDirectionENS_17tResampleEdgeModeERKNS_12FilterParamsE'/>
<use f='Modules/Image/Src/tResample.cpp' l='299' u='r' c='_ZN6tImage15KernelFilterBoxEPK9tColour4biiffNS_15FilterDirectionENS_17tResampleEdgeModeERKNS_12FilterParamsE'/>
<use f='Modules/Image/Src/tResample.cpp' l='332' u='a' c='_ZN6tImage20KernelFilterBilinearEPK9tColour4biiffNS_15FilterDirectionENS_17tResampleEdgeModeERKNS_12FilterParamsE'/>
<use f='Modules/Image/Src/tResample.cpp' l='334' u='r' c='_ZN6tImage20KernelFilterBilinearEPK9tColour4biiffNS_15FilterDirectionENS_17tResampleEdgeModeERKNS_12FilterParamsE'/>
<use f='Modules/Image/Src/tResample.cpp' l='402' u='w' c='_ZN6tImage19KernelFilterBicubicEPK9tColour4biiffNS_15FilterDirectionENS_17tResampleEdgeModeERKNS_12FilterParamsE'/>
<use f='Modules/Image/Src/tResample.cpp' l='413' u='r' c='_ZN6tImage19KernelFilterBicubicEPK9tColour4biiffNS_15FilterDirectionENS_17tResampleEdgeModeERKNS_12FilterParamsE'/>
<use f='Modules/Image/Src/tResample.cpp' l='450' u='w' c='_ZN6tImage19KernelFilterLanczosEPK9tColour4biiffNS_15FilterDirectionENS_17tResampleEdgeModeERKNS_12FilterParamsE'/>
<use f='Modules/Image/Src/tResample.cpp' l='461' u='r' c='_ZN6tImage19KernelFilterLanczosEPK9tColour4biiffNS_15FilterDirectionENS_17tResampleEdgeModeERKNS_12FilterParamsE'/>
<use f='Modules/Math/Src/tLinearAlgebra.cpp' l='191' u='r' c='_ZN5tMath4tMulERNS_5tVec4ERKNS_5tMat4ERKS0_'/>
<use f='Modules/Math/Src/tLinearAlgebra.cpp' l='192' u='r' c='_ZN5tMath4tMulERNS_5tVec4ERKNS_5tMat4ERKS0_'/>
<use f='Modules/Math/Src/tLinearAlgebra.cpp' l='193' u='r' c='_ZN5tMath4tMulERNS_5tVec4ERKNS_5tMat4ERKS0_'/>
<use f='Modules/Math/Src/tLinearAlgebra.cpp' l='194' u='r' c='_ZN5tMath4tMulERNS_5tVec4ERKNS_5tMat4ERKS0_'/>
<use f='Modules/Math/Src/tLinearAlgebra.cpp' l='862' u='w' c='_ZN5tMath16tMakeOrthoNormalERNS_5tMat4E'/>
<use f='Modules/Math/Src/tLinearAlgebra.cpp' l='862' u='w' c='_ZN5tMath16tMakeOrthoNormalERNS_5tMat4E'/>
<use f='Modules/Math/Src/tLinearAlgebra.cpp' l='862' u='w' c='_ZN5tMath16tMakeOrthoNormalERNS_5tMat4E'/>
<use f='Modules/Math/Src/tLinearAlgebra.cpp' l='862' u='w' c='_ZN5tMath16tMakeOrthoNormalERNS_5tMat4E'/>
<use f='Modules/Math/Src/tLinearAlgebra.cpp' l='883' u='w' c='_ZN5tMath17tMakeOrthoUniformERNS_5tMat4E'/>
<use f='Modules/Math/Src/tLinearAlgebra.cpp' l='883' u='w' c='_ZN5tMath17tMakeOrthoUniformERNS_5tMat4E'/>
<use f='Modules/Math/Src/tLinearAlgebra.cpp' l='883' u='w' c='_ZN5tMath17tMakeOrthoUniformERNS_5tMat4E'/>
<use f='Modules/Math/Src/tLinearAlgebra.cpp' l='883' u='w' c='_ZN5tMath17tMakeOrthoUniformERNS_5tMat4E'/>
<use f='Modules/Math/Src/tLinearAlgebra.cpp' l='896' u='w' c='_ZN5tMath20tMakeOrthoNonUniformERNS_5tMat4E'/>
<use f='Modules/Math/Src/tLinearAlgebra.cpp' l='908' u='w' c='_ZN5tMath20tMakeOrthoNonUniformERNS_5tMat4E'/>
<use f='Modules/Math/Src/tLinearAlgebra.cpp' l='908' u='w' c='_ZN5tMath20tMakeOrthoNonUniformERNS_5tMat4E'/>
<use f='Modules/Math/Src/tLinearAlgebra.cpp' l='908' u='w' c='_ZN5tMath20tMakeOrthoNonUniformERNS_5tMat4E'/>
<use f='Modules/Scene/Inc/Scene/tInstance.h' l='35' u='w' c='_ZN6tScene9tInstance5ScaleEf'/>
<use f='Modules/System/Src/tPrint.cpp' l='2021' u='r' c='_ZN7tSystem9Handler_mERNS_8ReceiverERKNS_10FormatSpecEPv'/>
<use f='Modules/System/Src/tPrint.cpp' l='2021' u='r' c='_ZN7tSystem9Handler_mERNS_8ReceiverERKNS_10FormatSpecEPv'/>
<use f='Modules/System/Src/tPrint.cpp' l='2021' u='r' c='_ZN7tSystem9Handler_mERNS_8ReceiverERKNS_10FormatSpecEPv'/>
<use f='Modules/System/Src/tPrint.cpp' l='2021' u='r' c='_ZN7tSystem9Handler_mERNS_8ReceiverERKNS_10FormatSpecEPv'/>
<use f='Modules/System/Src/tScript.cpp' l='335' u='w' c='_ZNK11tExpression14GetAtomVector4Ev'/>
