<use f='Modules/Math/Inc/Math/tGeometry.h' l='99' u='m' c='_ZN5tMath9tLineSeg2C1Effff'/>
<use f='Modules/Math/Inc/Math/tGeometry.h' l='100' u='w' c='_ZN5tMath9tLineSeg2C1ERKNS_8tVector2ES3_'/>
<use f='Modules/Math/Inc/Math/tGeometry.h' l='101' u='w' c='_ZN5tMath9tLineSeg2C1ERKS0_'/>
<use f='Modules/Math/Inc/Math/tGeometry.h' l='101' u='r' c='_ZN5tMath9tLineSeg2C1ERKS0_'/>
<dec f='Modules/Math/Inc/Math/tGeometry.h' l='102' type='tMath::tVector2'/>
<use f='Modules/Math/Inc/Math/tGeometry.h' l='112' u='r' c='_ZN5tMath6tLine2C1ERKNS_9tLineSeg2E'/>
<offset>64</offset>
<use f='Modules/Math/Src/tGeometry.cpp' l='324' u='m' c='_ZN5tMath20tIntersectFindSegSegERKNS_9tLineSeg2ES2_RNS_8tVector2E'/>
<use f='Modules/Math/Src/tGeometry.cpp' l='365' u='w' c='_ZN5tMath21tIntersectFindRayRectERKNS_5tRay2ERKNS_7tARect2EPNS_8tVector2EPj'/>
<use f='Modules/Math/Src/tGeometry.cpp' l='375' u='w' c='_ZN5tMath21tIntersectFindRayRectERKNS_5tRay2ERKNS_7tARect2EPNS_8tVector2EPj'/>
<use f='Modules/Math/Src/tGeometry.cpp' l='387' u='w' c='_ZN5tMath21tIntersectFindRayRectERKNS_5tRay2ERKNS_7tARect2EPNS_8tVector2EPj'/>
<use f='Modules/Math/Src/tGeometry.cpp' l='399' u='w' c='_ZN5tMath21tIntersectFindRayRectERKNS_5tRay2ERKNS_7tARect2EPNS_8tVector2EPj'/>
