<dec f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='127' type='float[3]'/>
<use f='Modules/Math/Inc/Math/tVector3.h' l='97' u='r' c='_ZN5tMath8tVector3cvPKfEv'/>
<use f='Modules/Math/Inc/Math/tVector3.h' l='98' u='r' c='_ZNK5tMath8tVector3cvPKfEv'/>
<use f='Modules/Math/Inc/Math/tVector3.h' l='99' u='a' c='_ZN5tMath8tVector3ixEi'/>
<use f='Modules/Math/Inc/Math/tVector3.h' l='100' u='r' c='_ZNK5tMath8tVector3ixEi'/>
<offset>0</offset>
<use f='Modules/Math/Src/tGeometry.cpp' l='64' u='r' c='_ZNK5tMath5tOBox8IsInsideERKNS_8tVector3E'/>
<use f='Modules/System/Src/tChunk.cpp' l='349' u='a' c='_ZN12tChunkWriter5WriteERKN5tMath8tVector3E'/>
<use f='Modules/System/Src/tChunk.cpp' l='465' u='a' c='_ZN12tChunkWriter5WriteERKN5tMath7tSphereE'/>
<use f='Modules/System/Src/tChunk.cpp' l='505' u='w' c='_ZN12tChunkWriter5WriteEPKN5tMath8tVector3Ei'/>
<use f='Modules/System/Src/tChunk.cpp' l='505' u='r' c='_ZN12tChunkWriter5WriteEPKN5tMath8tVector3Ei'/>
<use f='Modules/System/Src/tChunk.cpp' l='674' u='w' c='_ZN12tChunkWriter5WriteEPKN5tMath7tSphereEi'/>
<use f='Modules/System/Src/tChunk.cpp' l='674' u='r' c='_ZN12tChunkWriter5WriteEPKN5tMath7tSphereEi'/>
<use f='Modules/System/Src/tScript.cpp' l='786' u='r' c='_ZN11tExprWriter9WriteAtomERKN5tMath8tVector3Eb'/>
