<use f='Modules/Math/Inc/Math/tGeometry.h' l='250' u='w' c='_ZN5tMath5tLine3SetERKNS_4tRayE'/>
<use f='Modules/Math/Inc/Math/tGeometry.h' l='251' u='w' c='_ZN5tMath5tLine3SetERKNS_8tLineSegE'/>
<dec f='Modules/Math/Inc/Math/tGeometry.h' l='253' type='tMath::tVector3'/>
<offset>96</offset>
<use f='Modules/Math/Src/tGeometry.cpp' l='266' u='m' c='_ZN5tMath15tDistanceToLineERKNS_8tVector3ERKNS_5tLineE'/>
