<dec f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='167' type='float[4]'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='260' u='r' c='_ZN5tMath4tGetEPfRKNS_5tMat2E'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='260' u='r' c='_ZN5tMath4tGetEPfRKNS_5tMat2E'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='260' u='r' c='_ZN5tMath4tGetEPfRKNS_5tMat2E'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='260' u='r' c='_ZN5tMath4tGetEPfRKNS_5tMat2E'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='400' u='w' c='_ZN5tMath4tAddERNS_5tMat2ERKS0_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='400' u='r' c='_ZN5tMath4tAddERNS_5tMat2ERKS0_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='401' u='w' c='_ZN5tMath4tAddERNS_5tMat2ERKS0_S3_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='401' u='r' c='_ZN5tMath4tAddERNS_5tMat2ERKS0_S3_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='401' u='r' c='_ZN5tMath4tAddERNS_5tMat2ERKS0_S3_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='414' u='w' c='_ZN5tMath4tSubERNS_5tMat2ERKS0_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='414' u='r' c='_ZN5tMath4tSubERNS_5tMat2ERKS0_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='415' u='w' c='_ZN5tMath4tSubERNS_5tMat2ERKS0_S3_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='415' u='r' c='_ZN5tMath4tSubERNS_5tMat2ERKS0_S3_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='415' u='r' c='_ZN5tMath4tSubERNS_5tMat2ERKS0_S3_'/>
<offset>0</offset>
<use f='Modules/Math/Inc/Math/tMatrix2.h' l='74' u='r' c='_ZN5tMath8tMatrix2cvPKfEv'/>
<use f='Modules/Math/Inc/Math/tMatrix2.h' l='75' u='r' c='_ZNK5tMath8tMatrix2cvPKfEv'/>
<use f='Modules/Math/Inc/Math/tMatrix2.h' l='76' u='a' c='_ZN5tMath8tMatrix2ixEi'/>
<use f='Modules/Math/Inc/Math/tMatrix2.h' l='77' u='r' c='_ZNK5tMath8tMatrix2ixEi'/>
<use f='Modules/System/Src/tChunk.cpp' l='394' u='a' c='_ZN12tChunkWriter5WriteERKN5tMath8tMatrix2E'/>
<use f='Modules/System/Src/tChunk.cpp' l='568' u='w' c='_ZN12tChunkWriter5WriteEPKN5tMath8tMatrix2Ei'/>
<use f='Modules/System/Src/tChunk.cpp' l='568' u='r' c='_ZN12tChunkWriter5WriteEPKN5tMath8tMatrix2Ei'/>
<use f='Modules/System/Src/tScript.cpp' l='879' u='r' c='_ZN11tExprWriter9WriteAtomERKN5tMath8tMatrix2Eb'/>
