<dec f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='139' type='float'/>
<offset>96</offset>
<dec f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='138' type='float'/>
<offset>32</offset>
<use f='Modules/Math/Src/tLinearAlgebra.cpp' l='917' u='r' c='_ZN5tMath24tExtractProjectionPlanesEPNS_5tVec4ERKNS_5tMat4Ebb'/>
<use f='Modules/Math/Src/tLinearAlgebra.cpp' l='917' u='r' c='_ZN5tMath24tExtractProjectionPlanesEPNS_5tVec4ERKNS_5tMat4Ebb'/>
<use f='Modules/Math/Src/tLinearAlgebra.cpp' l='917' u='r' c='_ZN5tMath24tExtractProjectionPlanesEPNS_5tVec4ERKNS_5tMat4Ebb'/>
<use f='Modules/Math/Src/tLinearAlgebra.cpp' l='917' u='r' c='_ZN5tMath24tExtractProjectionPlanesEPNS_5tVec4ERKNS_5tMat4Ebb'/>
<use f='Modules/Math/Src/tLinearAlgebra.cpp' l='918' u='r' c='_ZN5tMath24tExtractProjectionPlanesEPNS_5tVec4ERKNS_5tMat4Ebb'/>
<use f='Modules/Math/Src/tLinearAlgebra.cpp' l='918' u='r' c='_ZN5tMath24tExtractProjectionPlanesEPNS_5tVec4ERKNS_5tMat4Ebb'/>
<use f='Modules/Math/Src/tLinearAlgebra.cpp' l='918' u='r' c='_ZN5tMath24tExtractProjectionPlanesEPNS_5tVec4ERKNS_5tMat4Ebb'/>
<use f='Modules/Math/Src/tLinearAlgebra.cpp' l='918' u='r' c='_ZN5tMath24tExtractProjectionPlanesEPNS_5tVec4ERKNS_5tMat4Ebb'/>
