<use f='Modules/Math/Inc/Math/tGeometry.h' l='261' u='w' c='_ZN5tMath9tCylinderC1ERKNS_8tVector3ES3_f'/>
<use f='Modules/Math/Inc/Math/tGeometry.h' l='262' u='w' c='_ZN5tMath9tCylinderC1ERKNS_8tLineSegEf'/>
<dec f='Modules/Math/Inc/Math/tGeometry.h' l='265' type='tMath::tVector3'/>
<use f='Modules/Math/Inc/Math/tGeometry.h' l='609' u='r' c='_ZN5tMath26tIntersectTestCapsulePointERKNS_9tCylinderERKNS_8tVector3E'/>
<offset>128</offset>
<use f='Modules/Math/Src/tRandom.cpp' l='242' u='m' c='_ZN5tMath7tRandom19tGetPointOnCylinderERKNS_9tCylinderERKNS0_10tGeneratorE'/>
<use f='Modules/Math/Src/tRandom.cpp' l='300' u='m' c='_ZN5tMath7tRandom19tGetPointInCylinderERKNS_9tCylinderERKNS0_10tGeneratorE'/>
