<dec f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='149' type='float'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='225' u='w' c='_ZN5tMath4tSetERNS_5tQuatEffff'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='226' u='w' c='_ZN5tMath4tSetERNS_5tQuatEPKf'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='256' u='r' c='_ZN5tMath4tGetERfS0_S0_S0_RKNS_5tQuatE'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='257' u='r' c='_ZN5tMath4tGetEPfRKNS_5tQuatE'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='277' u='w' c='_ZN5tMath5tZeroERNS_5tQuatE'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='278' u='w' c='_ZN5tMath5tZeroERNS_5tQuatEj'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='290' u='r' c='_ZN5tMath7tIsZeroERKNS_5tQuatE'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='291' u='r' c='_ZN5tMath7tIsZeroERKNS_5tQuatEj'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='305' u='r' c='_ZN5tMath12tApproxEqualERKNS_5tQuatES2_f'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='305' u='r' c='_ZN5tMath12tApproxEqualERKNS_5tQuatES2_f'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='306' u='r' c='_ZN5tMath12tApproxEqualERKNS_5tQuatES2_jf'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='306' u='r' c='_ZN5tMath12tApproxEqualERKNS_5tQuatES2_jf'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='318' u='r' c='_ZN5tMath6tEqualERKNS_5tQuatES2_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='318' u='r' c='_ZN5tMath6tEqualERKNS_5tQuatES2_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='319' u='r' c='_ZN5tMath6tEqualERKNS_5tQuatES2_j'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='319' u='r' c='_ZN5tMath6tEqualERKNS_5tQuatES2_j'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='331' u='r' c='_ZN5tMath9tNotEqualERKNS_5tQuatES2_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='331' u='r' c='_ZN5tMath9tNotEqualERKNS_5tQuatES2_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='332' u='r' c='_ZN5tMath9tNotEqualERKNS_5tQuatES2_j'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='332' u='r' c='_ZN5tMath9tNotEqualERKNS_5tQuatES2_j'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='341' u='r' c='_ZN5tMath9tLengthSqERKNS_5tQuatE'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='341' u='r' c='_ZN5tMath9tLengthSqERKNS_5tQuatE'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='356' u='w' c='_ZN5tMath10tNormalizeERNS_5tQuatE'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='361' u='w' c='_ZN5tMath19tNormalizeGetLengthERNS_5tQuatE'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='366' u='w' c='_ZN5tMath14tNormalizeSafeERNS_5tQuatE'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='371' u='w' c='_ZN5tMath23tNormalizeSafeGetLengthERNS_5tQuatE'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='384' u='w' c='_ZN5tMath14tNormalizeFastERNS_5tQuatE'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='389' u='w' c='_ZN5tMath18tNormalizeSafeFastERNS_5tQuatE'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='398' u='w' c='_ZN5tMath4tAddERNS_5tQuatERKS0_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='398' u='r' c='_ZN5tMath4tAddERNS_5tQuatERKS0_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='399' u='w' c='_ZN5tMath4tAddERNS_5tQuatERKS0_S3_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='399' u='r' c='_ZN5tMath4tAddERNS_5tQuatERKS0_S3_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='399' u='r' c='_ZN5tMath4tAddERNS_5tQuatERKS0_S3_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='412' u='w' c='_ZN5tMath4tSubERNS_5tQuatERKS0_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='412' u='r' c='_ZN5tMath4tSubERNS_5tQuatERKS0_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='413' u='w' c='_ZN5tMath4tSubERNS_5tQuatERKS0_S3_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='413' u='r' c='_ZN5tMath4tSubERNS_5tQuatERKS0_S3_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='413' u='r' c='_ZN5tMath4tSubERNS_5tQuatERKS0_S3_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='426' u='w' c='_ZN5tMath4tNegERNS_5tQuatE'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='426' u='r' c='_ZN5tMath4tNegERNS_5tQuatE'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='427' u='w' c='_ZN5tMath4tNegERNS_5tQuatERKS0_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='427' u='r' c='_ZN5tMath4tNegERNS_5tQuatERKS0_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='434' u='w' c='_ZN5tMath10tConjugateERNS_5tQuatE'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='434' u='r' c='_ZN5tMath10tConjugateERNS_5tQuatE'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='435' u='w' c='_ZN5tMath10tConjugateERNS_5tQuatERKS0_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='435' u='r' c='_ZN5tMath10tConjugateERNS_5tQuatERKS0_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='453' u='w' c='_ZN5tMath4tMulERNS_5tQuatEf'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='454' u='w' c='_ZN5tMath4tMulERNS_5tQuatERKS0_f'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='454' u='r' c='_ZN5tMath4tMulERNS_5tQuatERKS0_f'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='455' u='w' c='_ZN5tMath4tMulERNS_5tQuatEfRKS0_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='455' u='r' c='_ZN5tMath4tMulERNS_5tQuatEfRKS0_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='497' u='w' c='_ZN5tMath4tDivERNS_5tQuatEf'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='498' u='w' c='_ZN5tMath4tDivERNS_5tQuatERKS0_f'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='498' u='r' c='_ZN5tMath4tDivERNS_5tQuatERKS0_f'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='519' u='r' c='_ZN5tMath4tDotERKNS_5tQuatES2_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='519' u='r' c='_ZN5tMath4tDotERKNS_5tQuatES2_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='988' u='r' c='_ZN5tMath7tRotateERNS_5tVec3ERKNS_5tQuatE'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='994' u='r' c='_ZN5tMath7tRotateERNS_5tVec4ERKNS_5tQuatE'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='996' u='r' c='_ZN5tMath7tRotateERNS_5tVec4ERKNS_5tQuatE'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='997' u='r' c='_ZN5tMath7tRotateERNS_5tVec4ERKNS_5tQuatE'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='1004' u='r' c='_ZN5tMath4tMulERNS_5tQuatERKS0_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='1004' u='r' c='_ZN5tMath4tMulERNS_5tQuatERKS0_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='1005' u='r' c='_ZN5tMath4tMulERNS_5tQuatERKS0_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='1005' u='r' c='_ZN5tMath4tMulERNS_5tQuatERKS0_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='1006' u='r' c='_ZN5tMath4tMulERNS_5tQuatERKS0_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='1006' u='r' c='_ZN5tMath4tMulERNS_5tQuatERKS0_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='1007' u='r' c='_ZN5tMath4tMulERNS_5tQuatERKS0_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='1007' u='r' c='_ZN5tMath4tMulERNS_5tQuatERKS0_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='1014' u='r' c='_ZN5tMath4tMulERNS_5tQuatERKS0_S3_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='1014' u='r' c='_ZN5tMath4tMulERNS_5tQuatERKS0_S3_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='1015' u='w' c='_ZN5tMath4tMulERNS_5tQuatERKS0_S3_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='1015' u='r' c='_ZN5tMath4tMulERNS_5tQuatERKS0_S3_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='1015' u='r' c='_ZN5tMath4tMulERNS_5tQuatERKS0_S3_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='1016' u='r' c='_ZN5tMath4tMulERNS_5tQuatERKS0_S3_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='1016' u='r' c='_ZN5tMath4tMulERNS_5tQuatERKS0_S3_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='1017' u='r' c='_ZN5tMath4tMulERNS_5tQuatERKS0_S3_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='1017' u='r' c='_ZN5tMath4tMulERNS_5tQuatERKS0_S3_'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='1023' u='r' c='_ZN5tMath4tMulERNS_5tQuatERKNS_5tVec3E'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='1025' u='r' c='_ZN5tMath4tMulERNS_5tQuatERKNS_5tVec3E'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='1026' u='r' c='_ZN5tMath4tMulERNS_5tQuatERKNS_5tVec3E'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='1033' u='r' c='_ZN5tMath4tMulERNS_5tQuatERKS0_RKNS_5tVec3E'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='1035' u='r' c='_ZN5tMath4tMulERNS_5tQuatERKS0_RKNS_5tVec3E'/>
<use f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='1036' u='r' c='_ZN5tMath4tMulERNS_5tQuatERKS0_RKNS_5tVec3E'/>
<offset>32</offset>
<use f='Modules/Math/Src/tLinearAlgebra.cpp' l='79' u='w' c='_ZN5tMath4tSetERNS_5tQuatERKNS_5tMat4E'/>
<use f='Modules/Math/Src/tLinearAlgebra.cpp' l='91' u='w' c='_ZN5tMath4tSetERNS_5tQuatERKNS_5tMat4E'/>
<use f='Modules/Math/Src/tLinearAlgebra.cpp' l='98' u='w' c='_ZN5tMath4tSetERNS_5tQuatERKNS_5tMat4E'/>
<use f='Modules/Math/Src/tLinearAlgebra.cpp' l='110' u='w' c='_ZN5tMath4tSetERNS_5tQuatERKNS_5tMat4E'/>
<use f='Modules/Math/Src/tLinearAlgebra.cpp' l='127' u='r' c='_ZN5tMath4tSetERNS_5tMat4ERKNS_5tQuatE'/>
<use f='Modules/Math/Src/tLinearAlgebra.cpp' l='127' u='r' c='_ZN5tMath4tSetERNS_5tMat4ERKNS_5tQuatE'/>
<use f='Modules/Math/Src/tLinearAlgebra.cpp' l='130' u='r' c='_ZN5tMath4tSetERNS_5tMat4ERKNS_5tQuatE'/>
<use f='Modules/Math/Src/tLinearAlgebra.cpp' l='131' u='r' c='_ZN5tMath4tSetERNS_5tMat4ERKNS_5tQuatE'/>
<use f='Modules/Math/Src/tLinearAlgebra.cpp' l='135' u='r' c='_ZN5tMath4tSetERNS_5tMat4ERKNS_5tQuatE'/>
<use f='Modules/Math/Src/tLinearAlgebra.cpp' l='164' u='r' c='_ZN5tMath4tGetERNS_5tVec3ERfRKNS_5tQuatE'/>
<use f='Modules/Math/Src/tLinearAlgebra.cpp' l='256' u='w' c='_ZN5tMath6tSlerpERNS_5tQuatERKS0_S3_f'/>
<use f='Modules/Math/Src/tLinearAlgebra.cpp' l='256' u='r' c='_ZN5tMath6tSlerpERNS_5tQuatERKS0_S3_f'/>
<use f='Modules/Math/Src/tLinearAlgebra.cpp' l='256' u='r' c='_ZN5tMath6tSlerpERNS_5tQuatERKS0_S3_f'/>
<use f='Modules/Math/Src/tLinearAlgebra.cpp' l='307' u='w' c='_ZN5tMath6tSlerpERNS_5tQuatERKS0_S3_fNS_16tOrientationPathE'/>
<use f='Modules/Math/Src/tLinearAlgebra.cpp' l='307' u='r' c='_ZN5tMath6tSlerpERNS_5tQuatERKS0_S3_fNS_16tOrientationPathE'/>
<use f='Modules/Math/Src/tLinearAlgebra.cpp' l='307' u='r' c='_ZN5tMath6tSlerpERNS_5tQuatERKS0_S3_fNS_16tOrientationPathE'/>
<use f='Modules/Math/Src/tLinearAlgebra.cpp' l='346' u='w' c='_ZN5tMath6tNlerpERNS_5tQuatERKS0_S3_fNS_16tOrientationPathE'/>
<use f='Modules/Math/Src/tLinearAlgebra.cpp' l='346' u='r' c='_ZN5tMath6tNlerpERNS_5tQuatERKS0_S3_fNS_16tOrientationPathE'/>
<use f='Modules/Math/Src/tLinearAlgebra.cpp' l='346' u='r' c='_ZN5tMath6tNlerpERNS_5tQuatERKS0_S3_fNS_16tOrientationPathE'/>
<use f='Modules/System/Src/tPrint.cpp' l='1976' u='r' c='_ZN7tSystem9Handler_qERNS_8ReceiverERKNS_10FormatSpecEPv'/>
<use f='Modules/System/Src/tScript.cpp' l='350' u='w' c='_ZNK11tExpression17GetAtomQuaternionEv'/>
