<use f='Modules/Math/Inc/Math/tGeometry.h' l='110' u='m' c='_ZN5tMath6tLine2C1Effff'/>
<use f='Modules/Math/Inc/Math/tGeometry.h' l='111' u='w' c='_ZN5tMath6tLine2C1ERKNS_8tVector2ES3_'/>
<use f='Modules/Math/Inc/Math/tGeometry.h' l='112' u='w' c='_ZN5tMath6tLine2C1ERKNS_9tLineSeg2E'/>
<use f='Modules/Math/Inc/Math/tGeometry.h' l='113' u='w' c='_ZN5tMath6tLine2C1ERKS0_'/>
<use f='Modules/Math/Inc/Math/tGeometry.h' l='113' u='r' c='_ZN5tMath6tLine2C1ERKS0_'/>
<dec f='Modules/Math/Inc/Math/tGeometry.h' l='114' type='tMath::tVector2'/>
<offset>64</offset>
<use f='Modules/Math/Src/tGeometry.cpp' l='278' u='m' c='_ZN5tMathL27IntersectFindLineLineHelperERKNS_6tLine2ES2_RfS3_'/>
<use f='Modules/Math/Src/tGeometry.cpp' l='280' u='m' c='_ZN5tMathL27IntersectFindLineLineHelperERKNS_6tLine2ES2_RfS3_'/>
<use f='Modules/Math/Src/tGeometry.cpp' l='282' u='m' c='_ZN5tMathL27IntersectFindLineLineHelperERKNS_6tLine2ES2_RfS3_'/>
<use f='Modules/Math/Src/tGeometry.cpp' l='283' u='m' c='_ZN5tMathL27IntersectFindLineLineHelperERKNS_6tLine2ES2_RfS3_'/>
<use f='Modules/Math/Src/tGeometry.cpp' l='310' u='m' c='_ZN5tMath22tIntersectFindLineLineERKNS_6tLine2ES2_RNS_8tVector2E'/>
<use f='Modules/Math/Src/tGeometry.cpp' l='343' u='m' c='_ZN5tMath20tIntersectFindRaySegERKNS_5tRay2ERKNS_9tLineSeg2ERNS_8tVector2E'/>
