<dec f='Modules/Math/Inc/Math/tLinearAlgebra.h' l='151' type='float[4]'/>
<offset>0</offset>
<use f='Modules/Math/Inc/Math/tQuaternion.h' l='100' u='r' c='_ZN5tMath11tQuaternioncvPKfEv'/>
<use f='Modules/Math/Inc/Math/tQuaternion.h' l='101' u='r' c='_ZNK5tMath11tQuaternioncvPKfEv'/>
<use f='Modules/Math/Inc/Math/tQuaternion.h' l='102' u='a' c='_ZN5tMath11tQuaternionixEi'/>
<use f='Modules/Math/Inc/Math/tQuaternion.h' l='103' u='r' c='_ZNK5tMath11tQuaternionixEi'/>
<use f='Modules/System/Src/tChunk.cpp' l='379' u='a' c='_ZN12tChunkWriter5WriteERKN5tMath11tQuaternionE'/>
<use f='Modules/System/Src/tChunk.cpp' l='547' u='w' c='_ZN12tChunkWriter5WriteEPKN5tMath11tQuaternionEi'/>
<use f='Modules/System/Src/tChunk.cpp' l='547' u='r' c='_ZN12tChunkWriter5WriteEPKN5tMath11tQuaternionEi'/>
<use f='Modules/System/Src/tScript.cpp' l='848' u='r' c='_ZN11tExprWriter9WriteAtomERKN5tMath11tQuaternionEb'/>
